### ISSUE TITLE
Error with setup.sh on Linux

### ISSUE THREAD

**Issue by gabrielfgularte** [nu7hatch/angular-foundation-on-yeoman#3]
I'm on Ubuntu 12.04 LTS and I can't get setup.sh working. Seems like there's an sintaxe error in the code. Here's the terminal output:

```
./scripts/setup.sh: 3: ./scripts/setup.sh: function: not found
./scripts/setup.sh: 10: ./scripts/setup.sh: Syntax error: "}" unexpected
```

Thanks!

**Comment by gflarity** [comment]
This is because the script is really a bash script. It was probably written on a platform where sh = bash, but this not always the case.  Submitting a pull request.

**Comment by gabrielfgularte** [comment]
I can't test it anymore, did your PR solved the problem, @gflarity? If so, can you close this issue?
